### ISSUE TITLE
not compilable and executable

### ISSUE THREAD

**Issue by Adrian8115** [Sandertv/go-raknet#27]
When trying to execute a executable generated with this example code it fails:

```go
package main

import (
	"github.com/sandertv/go-raknet"
)

func main() {
	listener, _ := raknet.Listen("0.0.0.0:19132")
	listener.PongData([]byte("MCPE;Dedicated Server;120;1.20.50;1000;9999;13253860896781930865;Bedrock level;Survival;1;19132;19133;"))

	defer listener.Close()
	for {
		conn, _ := listener.Accept()

		b := make([]byte, 1024*1024*4)

		_, _ = conn.Read(b)
	}
}

```

The following error:
```
C:\Users\current_user\Test>Test.exe
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x9c62a9]

goroutine 1 [running]:
github.com/sandertv/go-raknet.(*Listener).PongData(0x0?, {0xc0000c6000?, 0x0?, 0x9ff13d?})
        C:/Users/current_user/go/pkg/mod/github.com/sandertv/go-raknet@v1.12.1/listener.go:139 +0x29
main.main()
        C:/Users/current_user/Test/main.go:9 +0x88
```

**Comment by Sandertv** [comment]
Please make sure to check all errors and report back.

**Comment by Adrian8115** [comment]
sorry my bad, ran another server on the same port
